apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microcrm-ingress
  namespace: microcrm-staging
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: microcrm-staging.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: microcrm-service
                port:
                  number: 8080
