apiVersion: v1
kind: ServiceAccount
metadata:
  name: microcrm-sa
  namespace: microcrm-staging
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: microcrm-reader
  namespace: microcrm-staging
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: microcrm-reader-binding
  namespace: microcrm-staging
subjects:
  - kind: ServiceAccount
    name: microcrm-sa
    namespace: microcrm-staging
roleRef:
  kind: Role
  name: microcrm-reader
  apiGroup: rbac.authorization.k8s.io
