apiVersion: v1
kind: Service
metadata:
  name: microcrm-service
  namespace: microcrm-staging
spec:
  selector:
    app: microcrm
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
